package com.belhard.task2.utils;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Map;
import java.util.Map.Entry;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

public class BuilderFormUtils {
	private static final String pathCss = "css/style.css";
	public static final String CHARSET_NAME = "UTF-8";

	public static PrintWriter buildHtmlForm (HttpServletRequest request, HttpServletResponse response) throws IOException{
		String sessionValue = "sessionValue";
		String sessionErr = "sessionErr";
		 
		String firstName = "firstName";
		String secondName = "secondName";
		String middleName = "middleName";
		String secretePhraze = "secretePhraze";
		String age = "age";
		String gender = "gender";
		String course = "course";
		String teacher = "teacher";
		String mark = "mark";
		String orderTest = "orderTest";
		String otherRecommendations = "otherRecommendations"; 
		String commercialOtherText = "commercialOtherText";
		String orderCommercial = "orderCommercial";
		String formValidation = "formValidation";
		String fieldOtherString = "fieldOtherString";

		@SuppressWarnings("unchecked")
		Map<String, Object> mapValue = (Map<String, Object>) request.getSession().getAttribute(sessionValue);
		String[] arrayTest = {"", "", ""};
		String[] arrayCourse = {"", "", ""};
		String[] arrayTeacher = {"", "", ""};
		String[] arrayMark = {"", "", "", "", "", "", "", "", "", ""};
		String[] arrayOtherCourses = {"", "", "", "", "", "", "", "", "", ""};
		String[] arrayAdversting = {"", "", "", "", "", ""};
		String firstNameInsert = "";
		String secondNameInsert = "";
		String middleNameInsert = "";
		String secretePhrazeInsert = "";
		String ageInsert = "";
		String commercialOtherTextInsert = "";
		String otherRecommendationsInsert = "";
		String formValidationInsert = "";
		if (mapValue != null) {
			arrayTest=(String[])mapValue.get(gender);  
			arrayCourse=(String[])mapValue.get(course);		
			arrayTeacher=(String[])mapValue.get(teacher);	 
			arrayMark=(String[])mapValue.get(mark);		
			arrayOtherCourses=(String[])mapValue.get(orderTest);		
			arrayAdversting=(String[])mapValue.get(orderCommercial);
			firstNameInsert = (String) mapValue.get(firstName);
			secondNameInsert = (String) mapValue.get(secondName);
			middleNameInsert = (String) mapValue.get(middleName);
			secretePhrazeInsert = (String) mapValue.get(secretePhraze);
			ageInsert = (String) mapValue.get(age);
			commercialOtherTextInsert = (String) mapValue.get(commercialOtherText);
			otherRecommendationsInsert = (String) mapValue.get(otherRecommendations);
			formValidationInsert = (String) mapValue.get(formValidation);
			}
		
		@SuppressWarnings("unchecked")
		Map<String, Object> mapErr = (Map<String, Object>) request.getSession().getAttribute(sessionErr);
		String firstNameErr = "hidden";
		String secondNameErr = "hidden";
		String secretePhrazeErr = "hidden";
		String ageErr = "hidden";
		String genderErr = "hidden";
		String courseErr = "hidden";
		String orderTestErr = "hidden";
		String orderCommercialErr = "hidden";
		String teacherErr = "hidden";
		String markErr = "hidden";
		String fieldOtherStringErr = "hidden";
  		if (mapValue != null) {
			firstNameErr = (String) mapErr.get(firstName);
			secondNameErr = (String) mapErr.get(secondName);
			secretePhrazeErr = (String) mapErr.get(secretePhraze);
			ageErr = (String) mapErr.get(age);
			genderErr = (String) mapErr.get(gender);
			courseErr = (String) mapErr.get(course);
			orderTestErr = (String) mapErr.get(orderTest);
			orderCommercialErr = (String) mapErr.get(orderCommercial);
			teacherErr = (String) mapErr.get(teacher);
			markErr = (String) mapErr.get(mark);
			fieldOtherStringErr = (String) mapErr.get(fieldOtherString);
			}

		PrintWriter writer=response.getWriter();
		writer.print("<!DOCTYPE html>");
		writer.print("<html lang=\"en\">");
		writer.print("<head>");
		writer.print("	<meta charset="+CHARSET_NAME+">");
		writer.print("	<link rel=\"stylesheet\" type=\"text/css\" href="+pathCss+">");
		writer.print("	<title>Document</title>");
		writer.print("<script type=\"text/javascript\" src=\"jquery-1.12.3.min.js\"></script>");
		writer.print("<script type=\"text/javascript\" src=\"scripts/script.js\"></script>");
		writer.print("<script>");
		writer.print("function myFunction55() {");
		writer.print("    document.getElementById(\"name2\").style.visibility = \"visible\";");
		writer.print(" }");
		writer.print("</script>");
		writer.print("<script>");
		writer.print("function myFunction56() {");
		writer.print("document.getElementById(\"name2\").style.visibility = \"hidden\";");
		writer.print("}");
		writer.print("</script>");
		writer.print("<script>");
		writer.print("function myFunction57() {");
		writer.print("if (document.getElementById(\"name2\").value=='') {document.getElementById(\"name2\").style.visibility = \"hidden\";}");
		writer.print("}");
		writer.print("</script>");
		writer.print("<script>");
		writer.print("function myFunction70() {");
		writer.print("document.getElementById(\"r1\").style.visibility = \"visible\";");
		writer.print("}");
		writer.print("</script>");
		writer.print("<script>");
		writer.print("function myFunction71() {");
		writer.print("document.getElementById(\"r1\").style.visibility = \"hidden\";");
		writer.print("}");
		writer.print("</script>");
		writer.print("<script type=\"text/javascript\">");
		writer.print("jQuery(document).ready(function($) {");
		writer.print("var requiredCheckboxes = $(':checkbox[required]');");
		writer.print("requiredCheckboxes.on('change', function(e) {");
		writer.print("var checkboxGroup = requiredCheckboxes.filter('[name=\"' + $(this).attr('name') + '\"]');");
		writer.print("var isChecked = checkboxGroup.is(':checked');");
		writer.print("checkboxGroup.prop('required', !isChecked);");
		writer.print("});");
		writer.print("});");
		writer.print("</script>");
		writer.print("<script type=\"text/javascript\">");
		writer.print("function hc()");
		writer.print("{");
		writer.print("if(document.getElementById('JavaSE').id=='JavaSE') {");
		writer.print("document.getElementById('JavaEE').removeAttribute('disabled');");
		writer.print("document.getElementById('Testing').removeAttribute('disabled');");
		writer.print("}");
		writer.print("}");
		writer.print("function hc2()");
		writer.print("{");
		writer.print("if(document.getElementById('JavaEE').id=='JavaEE') {");
		writer.print("document.getElementById('JavaSE').removeAttribute('disabled');");
		writer.print("document.getElementById('Testing').removeAttribute('disabled');");
		writer.print("}");
		writer.print("}");
		writer.print("function hc3()");
		writer.print("{");
		writer.print("if(document.getElementById('Testing').id=='Testing') {");
		writer.print("document.getElementById('JavaSE').removeAttribute('disabled');");
		writer.print("document.getElementById('JavaEE').removeAttribute('disabled');");
		writer.print("}");
		writer.print("}");
		writer.print("</script>");
		writer.print("<script>function myFunction11() {");
		writer.print("alert('dsds');");
		writer.print("document.getElementById(\"a7\").value='fff';");
		writer.print("}");
		writer.print("</script>");
		writer.print("<script>");
		writer.print("function myFunction3() {");
		writer.print("var fail=false;");
		writer.print("var x=document.getElementById(\"a1\").value;");
		writer.print("var x_pattern=/[a-zA-Z]/i;");
		writer.print("if (x==\"\" || x_pattern.test(x)==false) fail='Second name can not be empty or number';");
		writer.print("var x1=document.getElementById(\"a2\").value;");
		writer.print("var x1_pattern=/[a-zA-Z]/i;");
		writer.print("if (x1==\"\" || x1_pattern.test(x1)==false) fail1='First name can not be empty or number';");
		writer.print("var x2=document.getElementById(\"family\").value;");
		writer.print("var x2_pattern=/[a-zA-Z]/i;");
		writer.print("if (x2==\"\" || x2_pattern.test(x2)==false) fail2='Middle name can not be empty or number';");
		writer.print("var x3=document.getElementById(\"a4\").value;");
		writer.print("var x3_pattern=/[a-zA-Z]/i;");
		writer.print("if (x3==\"\" || x3_pattern.test(x3)==false) fail3='secretePhraze can not be empty or number';");
		writer.print("var x5=document.getElementById(\"a7\").value;");
		writer.print("var x5_pattern=/[1-9]{1}/;");
		writer.print("if ( x5_pattern.test(x5)==false) fail5='gender can be Male or Female';");
		writer.print("var x6=document.getElementById(\"a8\").value;");
		writer.print("var x6_pattern=/[1-9]{1}/;");
		writer.print("if ( x6_pattern.test(x6)==false) fail6='Course can not be empty';");
		writer.print("var x7=document.getElementById(\"a9\").value;");
		writer.print("var x7_pattern=/[1-9]{1}/;");
		writer.print("if ( x7_pattern.test(x7)==false) fail7='Mentor can not be empty';");
		writer.print("var x8=document.getElementById(\"b10\").value;");
		writer.print("var x8_pattern=/[1-9]{1}/;");
		writer.print("if ( x8_pattern.test(x8)==false) fail8='Mark of courses can not be empty';");
		writer.print("var x9=document.getElementById(\"a11\").value;");
		writer.print("var x9_pattern=/[1-9]{1}/;");
		writer.print("if ( x9_pattern.test(x9)==false) fail9='otherCourse can not be empty';");
		writer.print("var x10=document.getElementById(\"b12\").value;");
		writer.print("var x10_pattern=/[1-9]{1}/;");
		writer.print("if ( x10_pattern.test(x10)==false) fail10='Question: how did you known about us, can not be empty';");
		writer.print("var x11=document.getElementById(\"a5\").value;");
		writer.print("var x11_pattern=/[1]{1}[8-9]{1}|[2-9]{1}[0-9]{1}/;");
		writer.print("if ( x11_pattern.test(x11)==false) fail11='Age have to be at 18 to 99';");
		writer.print("if((document.getElementById(\"a30\").checked==false) && (x==\"\" || x_pattern.test(x)==false)) { alert(fail);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && (x1==\"\" || x1_pattern.test(x1)==false)) { alert(fail1);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && (x2==\"\" || x2_pattern.test(x2)==false)) {/ alert(fail2);  return false;/}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && (x3==\"\" || x3_pattern.test(x3)==false)) { alert(fail3);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && (x11_pattern.test(x11)==false)) { alert(fail11);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && ( x5_pattern.test(x5)==false)) { alert(fail5);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && ( x6_pattern.test(x6)==false)) { alert(fail6);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && ( x7_pattern.test(x7)==false)) { alert(fail7);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && ( x8_pattern.test(x8)==false)) { alert(fail8);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && ( x9_pattern.test(x9)==false)) { alert(fail9);  return false;}");
		writer.print("if((document.getElementById(\"a30\").checked==false) && ( x10_pattern.test(x10)==false)) { alert(fail10);  return false;}");
		writer.print("if (document.getElementById(\"a30\").checked==true || x!=\"\") {");
		writer.print("if (document.getElementById(\"rrr\").value == '2') {");
		writer.print("var r = confirm(\"In fact, lying is not good, even if you do not see ... Just send?\");");
		writer.print("if (r == true) {");
		writer.print("var coffee = document.forms[0];");
		writer.print("var txt = \"\";");
		writer.print("var i;");
		writer.print("for (i = 0; i < 10; i++) {");
		writer.print("if (document.b.otherCourse.options[i].selected==true) {");
		writer.print("txt = txt  + document.b.otherCourse.options[i].value + \", \"");
		writer.print("}");
		writer.print("}");
		writer.print("document.getElementById(\"orderTest\").value = txt ;");
		writer.print("var coffee1 = document.forms[0];");
		writer.print("var txt1 = \"\";");
		writer.print("var i1;");
		writer.print("for (i1 = 0; i1 < coffee1.length; i1++) {");
		writer.print("if (coffee1[i1].id=='commercial' && coffee1[i1].checked==true) {");
		writer.print("txt1 = txt1 + coffee1[i1].value + \", \";");
		writer.print("}");
		writer.print("}");
		writer.print("document.getElementById(\"orderCommercial\").value = txt1;");
		writer.print("}");
		writer.print("else {");
		writer.print("return false;");
		writer.print("}");
		writer.print("}");
		writer.print("if (document.getElementById(\"rrr\").value == '3') {");
		writer.print("var r = alert(\"Bravo, honest man! Feel free to go to watch the result!\");");
		writer.print("var coffee = document.forms[0];");
		writer.print("var txt = \"\";");
		writer.print("var i;");
		writer.print("for (i = 0; i < 10; i++) {");
		writer.print("if (document.b.otherCourse.options[i].selected==true) {");
		writer.print("txt = txt  + document.b.otherCourse.options[i].value + \", \"");
		writer.print("}");
		writer.print("}");
		writer.print("document.getElementById(\"orderTest\").value = txt ;");
		writer.print("var coffee1 = document.forms[0];");
		writer.print("var txt1 = \"\";");
		writer.print("var i1;");
		writer.print("for (i1 = 0; i1 < coffee1.length; i1++) {");
		writer.print("if (coffee1[i1].id=='commercial' && coffee1[i1].checked==true) {");
		writer.print("txt1 = txt1 + coffee1[i1].value + \", \";");
		writer.print("}");
		writer.print("}");
		writer.print("document.getElementById(\"orderCommercial\").value = txt1;");
		writer.print("}");
		writer.print("}");
		writer.print("}");
		writer.print("</script>");
		writer.print("<script>function myFunction5() {");
		writer.print("document.getElementById(\"rrr\").value = 2;");
		writer.print("document.getElementById(\"statusButton\").value = 'lie';}");
		writer.print("</script>");
		writer.print("<script>function myFunction6() {");
		writer.print("document.getElementById(\"rrr\").value = 3;");
		writer.print("document.getElementById(\"statusButton\").value = 'verity';}");
		writer.print("</script>");
		writer.print("<script>function myFunction10() {");
		writer.print("document.getElementById(\"a1\").required=\"false\";alert(\"hallo2\");");
		writer.print("}");
		writer.print("</script>");
		writer.print("</script>");
		
        writer.print("</head>");
        writer.print("<body  onload=\"myFunction57();myFunction72()\">");		
        writer.print("<form action=\"ValidationServlet\" method=\"get\" name=\"b\"  onsubmit=\"return myFunction3()\"  id=\"ooo\" >");
        writer.print("<div id=\"testBlock5\"><span class=\"headline\">Questionnaire</span> <br>");
        writer.print("<table width=\"70%\" cellspacing=\"4\" cellpadding=\"4\">");
        writer.print("<tr>");
        writer.print("<td align=\"right\" width=\"190\" height=\"25\"><b>Second name </b></td>");
        writer.print("<td width=\"200\"><input  type=\"text\" name=\"secondName\"  id=\"a1\"  title=\"«Second name is wrong format or empty!\"  value="+secondNameInsert+" ></td>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+secondNameErr+" id=\"r1\">Second name is wrong format or empty!</td>");
        writer.print("");
        writer.print("</tr>");
        writer.print("<tr>");
        writer.print("<td align=\"right\" height=\"25\"><b>First name </b></td>");
        writer.print("<td><input type=\"text\" name=\"firstName\" id=\"a2\"  title=\"«First name is wrong format or empty!\" value="+firstNameInsert+" ></td>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+firstNameErr+" id=\"r1\">First name is wrong format or empty!</td>");       
        writer.print("</tr> ");
        writer.print("<tr> ");
        writer.print("<td align=\"right\" height=\"25\" ><b>Middle name* </b></td>");
        writer.print("<td><input type=\"text\"  name=\"middleName\" id=\"family\" value="+middleNameInsert+"  ></td>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" hidden id=\"r1\">Middle name is wrong format or empty!</td>");       
        writer.print("</tr> ");
        writer.print("<tr> ");
        writer.print("<td align=\"right\" height=\"25\"><b>Secrete phraze </b></td>");
        writer.print("<td><input type=\"password\"  id=\"a4\"  name=\"secretePhraze\"  title=\"Secret phrase can not be empty.\" value="+secretePhrazeInsert+" ></td>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+secretePhrazeErr+" id=\"r1\">Secrete phraze is wrong format or empty!</td>");          
        writer.print("</tr>");
        writer.print("<tr>");
        writer.print("<td align=\"right\" height=\"25\"><b>Age </b></td>");
        writer.print("<td><input type=\"text\" name=\"age\"  title=\"Age is measured by whole numbers.\" id=\"a5\" value="+ageInsert+"></td>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+ageErr+" id=\"r1\">Age is wrong format or empty!</td>");       
        writer.print("</tr> ");
        writer.print("<tr>");
        writer.print("<td align=\"right\" width=\"130\" height=\"25\"><b>Gender </b></td>");
        writer.print("<td><input type=\"radio\" "+arrayTest[0]+" name=\"gender\" value=\"Male\" id=\"a6\" title=\"Gender must be specified.\" onclick=\"document.getElementById('a7').value=6;\">Male");
        writer.print("<input type=\"radio\" "+arrayTest[1]+" name=\"gender\" value=\"Female\" onclick=\"document.getElementById('a7').value=6;\" >Female<br></td>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+genderErr+" id=\"r1\">Gender is empty!</td>");   
        writer.print("</tr>");
        writer.print("<tr>");
         
        writer.print("<td valign=\"top\" align=\"right\" height=\"25\"><b>Course </b></td>");
        writer.print("<td><select name=\"course\" size=\"3\"   title=\"One course must be selected.\">	");
        writer.print("<option "+arrayCourse[0]+" title=\"Please do your choice\" value=\"JavaSE\"  onclick=\"var input = document.getElementById('JavaSE'); document.getElementById('a8').value=6; if(this.checked){ input.disabled = false; input.focus();}else{input.disabled=true;}; hc(this);\" >Java SE</option>");
        writer.print("<option "+arrayCourse[1]+" value=\"JavaEE\" onclick=\"var input = document.getElementById('JavaEE'); document.getElementById('a8').value=6;if(this.checked){ input.disabled = false; input.focus();}else{input.disabled=true;}; hc2(this); \">Java EE</option>");
        writer.print("<option "+arrayCourse[2]+" value=\"Testing\" onclick=\"var input = document.getElementById('Testing');document.getElementById('a8').value=6; if(this.checked){ input.disabled = false; input.focus();}else{input.disabled=true;}; hc3(this);\">Testing</option>");
        writer.print("</select>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+courseErr+" id=\"r1\">Course is empty!</td>");      
        writer.print("</tr>");
        writer.print("<tr>");
        writer.print("<td align=\"right\" height=\"25\"><b>Mentor </b></td>");
        writer.print("<td><select name=\"teacher\" title=\"Specify the teacher who taught the course.\" onclick=\"document.getElementById('a9').value=6;\">");
        writer.print("<option  value=\"\" name=\"pr\">Choice...</option>");
        writer.print("<option "+arrayTeacher[0]+" value=\"Ivanov Ivan Ivanovich\" name=\"pr\" onclick=\"document.getElementById('a9').value=6;\">Ivanov Ivan Ivanovich</option>");
        writer.print("<option "+arrayTeacher[1]+" value=\"Petrov Petr Petrovich\" name=\"pr\" onclick=\"document.getElementById('a9').value=6;\">Petrov Petr Petrovich </option>");
        writer.print("<option "+arrayTeacher[2]+" value=\"Sidorov Sidor Sidorovich\" name=\"pr\" onclick=\"document.getElementById('a9').value=6;\">Sidorov Sidor Sidorovich</option>");
        writer.print("</select>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+teacherErr+" id=\"r1\">Mentor is empty!</td>"); 
        writer.print("</tr>");
        writer.print("<tr>");       
            
        writer.print("<td align=\"right\" height=\"25\"><b>Mark of courses </b></td>");
        writer.print("<td><select name=\"mark\" size=\"1\" title=\"Specify how you assess the course.\" onclick=\"document.getElementById('b10').value=6;\">");
        writer.print("<option value=\"\" onclick=\"document.getElementById('b10').value=6;\">Choice...</option>");
        writer.print("<option "+arrayMark[0]+" value=\"10\" onclick=\"document.getElementById('b10').value=6;\">10</option>");
        writer.print("<option "+arrayMark[1]+" value=\"9\" onclick=\"document.getElementById('b10').value=6;\">9</option>");
        writer.print("<option "+arrayMark[2]+" value=\"8\" onclick=\"document.getElementById('b10').value=6;\">8</option>");
        writer.print("<option "+arrayMark[3]+" value=\"7\" onclick=\"document.getElementById('b10').value=6;\">7</option>");
        writer.print("<option "+arrayMark[4]+" value=\"6\" onclick=\"document.getElementById('b10').value=6;\">6</option>");
        writer.print("<option "+arrayMark[5]+" value=\"5\" onclick=\"document.getElementById('b10').value=6;\">5</option>");
        writer.print("<option "+arrayMark[6]+" value=\"4\" onclick=\"document.getElementById('b10').value=6;\">4</option>");
        writer.print("<option "+arrayMark[7]+" value=\"3\" onclick=\"document.getElementById('b10').value=6;\">3</option>");
        writer.print("<option "+arrayMark[8]+" value=\"2\" onclick=\"document.getElementById('b10').value=6;\">2</option>");
        writer.print("<option "+arrayMark[9]+" value=\"1\" onclick=\"document.getElementById('b10').value=6;\">1</option>");
        writer.print("</select>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+markErr+" id=\"r1\">Mark is empty!</td>");  
        writer.print("</tr>");
        writer.print("<tr>");
        writer.print("<td valign=\"top\" align=\"right\" height=\"25\"><b>Other courses </b></td>");
        writer.print("<td ><select id = \"selLanguage\" multiple = \"multiple\" size = \"10\" name=\"otherCourse\">");
        writer.print("<option "+arrayOtherCourses[0]+" value = \"HTML\" id=\"f\" onclick=\"document.getElementById('a11').value=6;\">HTML</option>");
        writer.print("<option "+arrayOtherCourses[1]+" value = \"CSS\" id=\"f\" onclick=\"document.getElementById('a11').value=6;\">CSS</option>");
        writer.print("<option "+arrayOtherCourses[2]+" value = \"JavaScript\" id=\"f\" onclick=\"document.getElementById('a11').value=6;\">JavaScript</option>");
        writer.print("<option "+arrayOtherCourses[3]+" value = \"PHP\" id=\"f\" onclick=\"document.getElementById('a11').value=6;\">PHP</option>");
        writer.print("<option "+arrayOtherCourses[4]+" value = \"MySQL\" id=\"f\" onclick=\"document.getElementById('a11').value=6;\">MySQL</option>");
        writer.print("<option "+arrayOtherCourses[5]+" value = \"Python\" id=\"f\" onclick=\"document.getElementById('a11').value=6;\">Python</option>");       
        writer.print("<option "+arrayOtherCourses[6]+" value = \"Flash\" id=\"f\" onclick=\"document.getElementById('a11').value=6;\">Flash</option>");
        writer.print("<option "+arrayOtherCourses[7]+" value = \"JavaSE\" id=\"JavaSE\" onclick=\"document.getElementById('a11').value=6;\">Java SE</option>");
        writer.print("<option "+arrayOtherCourses[8]+" value = \"JavaEE\" id=\"JavaEE\" onclick=\"document.getElementById('a11').value=6;\">Java EE</option>");
        writer.print("<option "+arrayOtherCourses[9]+" value = \"Тестирование\" id=\"Testing\" onclick=\"document.getElementById('a11').value=6;\">Testing</option> ");
        writer.print("</select>");
        writer.print("<td height=\"10\" align=\"left\"><table ><tr><td   class=\"bold_cell\" height=\"10\" "+orderTestErr+" id=\"r1\" width=\"510\" >Other courses is empty!</td></tr><tr><td><font color=\"ffffff\">ddd</font></td></tr><tr><td>");
        writer.print("<font color=\"ffffff\">ddd</font></td></tr><tr><td><font color=\"ffffff\">ddd</font></td></tr><tr><td><font color=\"ffffff\">ddd</font></td></tr><tr><td><font color=\"");
        writer.print("ffffff\">ddd</font></td></tr><tr><td><font color=\"ffffff\">ddd</font></td></tr></table></td>");
        writer.print("</td>");
        writer.print("</tr>");
        writer.print("<tr>");
        writer.print("<td align=\"right\" height=\"25\"><b>How did you hear about us: </b></td>");
        writer.print("<td width=\"25\"><input  type=\"checkbox\" "+arrayAdversting[0]+" name=\"commercial\" value=\"Advertising in the Tv\"  title=\"It must be selected at least one option.\" id=\"commercial\" onclick=\"document.getElementById('b12').value=6;\">Advertising in the Tv</td>");
        writer.print("<td align=\"left\"><input type=\"checkbox\" "+arrayAdversting[1]+" name=\"commercial\" value=\"Advertising in the radio\"  id=\"commercial\" onclick=\"document.getElementById('b12').value=6;\">Advertising in the radio</td>");
        writer.print("<td align=\"left\"  class=\"bold_cell\" width=\"250\" height=\"10\" "+orderCommercialErr+" id=\"r1\">How did you hear about us - is empty!</td>"); 
        writer.print("</tr>");      
        writer.print("<tr>");
        writer.print("<td></td><td width=\"25\"><input type=\"checkbox\" "+arrayAdversting[2]+" name=\"commercial\" value=\"Advertising in the internet\"  id=\"commercial\" onclick=\"document.getElementById('b12').value=6;\">Advertising in the internet</td>");
        writer.print("<td align=\"left\"><input type=\"checkbox\" "+arrayAdversting[3]+" name=\"commercial\" value=\"Advertising in the underground\"  id=\"commercial\" onclick=\"document.getElementById('b12').value=6;\">Advertising in the underground</td>");
        writer.print("</tr>");
        writer.print("<tr>");
        writer.print("<td></td><td width=\"25\"><input type=\"checkbox\" "+arrayAdversting[4]+" name=\"commercial\" value=\"Advertising in the newspaper\"  id=\"commercial\" onclick=\"document.getElementById('b12').value=6;\">Advertising in the newspaper</td>");
        writer.print("<td align=\"left\">");
        writer.print("<input type=\"checkbox\" id=\"commercial\" "+arrayAdversting[5]+" name=\"commercial\" value=\"Other\" onclick=\"var input = document.getElementById('name2');document.getElementById('b12').value=6; if(this.checked){ input.disabled = false; input.focus();myFunction55();}else{input.disabled=true;myFunction56();}\">Other</td>");
        writer.print("</tr>");
        writer.print("<tr > ");
        writer.print("	<td  valign=\"top\" align=\"right\" height=\"25\"  ><b id=\"name3\" name=\"name3\" style=\"display: none\">Other: </b></td>");
        writer.print("<td ><textarea rows=\"2\" cols=\"25\" name=\"commercialOtherText\"  id=\"name2\"   title=\"Reject - to offer!\">"+commercialOtherTextInsert+"</textarea></td>"); 
        writer.print("<td align=\"left\"  class=\"bold_cell\" height=\"10\" "+fieldOtherStringErr+" id=\"r1\">Other advertising is empty or wrong format!</td>"); 
        writer.print("</tr>");
        writer.print("<tr > ");
        writer.print("	<td align=\"right\" valign=\"top\"><b>Other recomendations*:</b></td>");
        writer.print("<td><textarea rows=\"3\" cols=\"25\" name=\"otherRecommendations\" id=\"name5\" title=\"Reject - to offer!\">"+otherRecommendationsInsert+"</textarea></td>");
        writer.print("</tr> ");
        writer.print("<tr >");
        writer.print("<td align=\"right\"><input type=\"submit\" value=\"Send - here's all true\"  id=\"ok\" onclick=\"myFunction6()\" ></td>");
        writer.print("	<td><input type=\"submit\" value=\"Send - I'm still all lied\" id=\"warning\"  onclick=\"myFunction5()\" ></td>");
        writer.print("<input type=\"text\" id=\"orderTest\" name=\"orderTest\" hidden=\"true\">");
        writer.print("<input type=\"text\" id=\"orderCommercial\" name=\"orderCommercial\"  hidden=\"true\">");
        writer.print("<input type=\"text\" id=\"rrr\" name=\"rrr\" hidden=\"true\" value=\"1\">");
        writer.print("<input type=\"text\" id=\"statusButton\" name=\"statusButton\" hidden=\"true\" value=\"none\">");      
        writer.print("</tr> ");
        writer.print("<tr > ");
        writer.print("<td align=\"right\" ><b>Form-validation:</b></td> ");
        writer.print("<td><p><input type=\"checkbox\" name=\"formValidation\" "+formValidationInsert+" value=\"true\" id=\"a30\" onclick=\"if(this.checked){myFunction70();}else{myFunction71();}\">Disable</p><input name=\"ttt\" value=\"ttt\" id=\"a7\" hidden=\"true\" >");
        writer.print("<input name=\"ttt\" value=\"ttt\" id=\"a9\"  hidden=\"true\" ><input name=\"ttt\" value=\"ttt\" id=\"a8\"  hidden=\"true\" ><input name=\"ttt\" value=\"ttt\" id=\"b10\"  hidden=\"true\" ><input name=\"ttt\" value=\"ttt\" id=\"a11\"  hidden=\"true\" ><input name=\"ttt\" value=\"ttt\" id=\"b12\"  hidden=\"true\" >");
        writer.print("</td>");
        writer.print("</tr> ");
        writer.print("</tr>");
        writer.print("</table></div>"); 
        writer.print("</form>");
        writer.print("<br><p align=\"center\" id=\"small\"> * The fields are optional to fill</p>");
        writer.print("</body>");
        writer.print("</html>");
        writer.print("");
 		return writer; 
	}
	
	public static  PrintWriter resultAllInformation(Map<String, Object> map1, Map<String, Object> map2, HttpServletResponse response) throws IOException {
		Map<String, Object> mapErr = map1;
		Map<String, Object> mapValue = map2;
		String empty = "";
		String nameOfHtmlFormServlet = "HtmlFormServlet";
		String firstName = "firstName";
		String secondName = "secondName";
		String middleName = "middleName";
		String secretePhraze = "secretePhraze";
		String age = "age";
		String gender = "gender";
		String course = "course";
		String teacher = "teacher";
		String mark = "mark";
		String orderTest = "orderTest";
		String otherRecommendations = "otherRecommendations";
		String commercialOtherText = "commercialOtherText";
		String orderCommercial = "orderCommercial";
		int counterError = 0;
		for(Entry<String, Object> entry : mapErr.entrySet()) {
		    String value = (String) entry.getValue();
		    if(value.equals(empty)){
		    	counterError++;	
		    } 
		}  
		PrintWriter writer = response.getWriter();
		if (counterError != 0) {
			response.sendRedirect(nameOfHtmlFormServlet); 
		} else 
		writer.print("<p>");
		writer.print("</p>");
		writer.print("<head>");
		writer.print("</head>");
		writer.print("<body>");
		writer.print("<p>");
		writer.print("Name of studens- "+ HttpUtils.getParameterValue(mapValue, firstName) +  " " + HttpUtils.getParameterValue(mapValue, secondName) + " " + HttpUtils.getParameterValue(mapValue, middleName) + "." + "<br>");
		writer.print(" Age - " + HttpUtils.getParameterValue(mapValue, age) + " years old. " + "<br>" + "Gender - " + HttpUtils.getParameterValueGender(mapValue, gender) + ". " + "<br>");
		writer.print("Secrete phraze - " + HttpUtils.getParameterValue(mapValue, secretePhraze) + ". " + "<br>");
		writer.print("Name of the training course - " + HttpUtils.getParameterValueCourse(mapValue, course) + ". " + "<br>");
		writer.print("The teacher conducting the course - "	+ HttpUtils.getParameterValueTeacher(mapValue, teacher) + ". " + "<br>");
		writer.print("The mark of the course set by the student - " + HttpUtils.getParameterValueMark(mapValue, mark) + ". " + "<br>");
		writer.print("Students have learned other courses - "+ HttpUtils.getParameterValueOtherCourses(mapValue, orderTest) + ". " + "<br>");
		writer.print("How did you hear about us - "+ HttpUtils.getParameterValueAdversting(mapValue, orderCommercial) + ". " + "<br>");
		writer.print(HttpUtils.getParameterValueAdverstingOther(mapValue, orderCommercial, commercialOtherText));
		writer.print(HttpUtils.getParameterValueOtherRecommendations(mapValue, otherRecommendations)); 
		return writer; 
	}
}
